Name:           g2o
Version:        2016.4.24
Release:        2%{?dist}
Summary:        A General Framework for Graph Optimization

License:        BSD
URL:            https://github.com/RainerKuemmerle/g2o
Source0:        https://github.com/RainerKuemmerle/g2o/archive/20160424_git.tar.gz#/%{name}-%{version}.tar.gz
Patch0:         g2o.libsuffix.patch

Conflicts:      ros-kinetic-libg2o
Obsoletes:      ros-kinetic-libg2o <= 2016.4.24-1

Requires:       boost-devel
Requires:       eigen3-devel
Requires:       mesa-libGL-devel
Requires:       mesa-libGLU-devel
Requires:       suitesparse-devel
BuildRequires:  boost-devel
BuildRequires:  cmake
BuildRequires:  eigen3-devel
BuildRequires:  mesa-libGL-devel
BuildRequires:  mesa-libGLU-devel
BuildRequires:  suitesparse-devel

%description
The libg2o library from http://openslam.org/g2o.html

%prep
%autosetup -p1 -n %{name}-20160424_git

%build
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

%make_build

%install
pushd obj-%{_target_platform}
%make_install

%files
%{_bindir}/*
%{_libdir}/*
%{_includedir}/*

%changelog
* Wed May 03 2017 Till Hofmann <till.hofmann@posteo.de> - 2016.4.24-2
- Rename to g2o
- Switch to repository RainerKuemmerle/g2o
- Clean up Spec file

* Tue May 02 2017 Nicolas Limpert <nicolas.limpert@alumni.fh-aachen.de> - 2016.4.24-1
- changed install-target to /usr

* Mon Apr 25 2016 Vincent Rabaud <vincent.rabaud@gmail.com> - 2016.4.24-0
- Autogenerated by Bloom

* Mon Apr 25 2016 Vincent Rabaud <vincent.rabaud@gmail.com> - 2016.4.12-0
- Autogenerated by Bloom

