%global version_major 2020
%global version_minor 12
%global version_patch 23
%global gittag %{version_major}%{version_minor}%{version_patch}_git
Name:           g2o
Version:        %{version_major}.%{version_minor}.%{version_patch}
Release:        1%{?dist}
Summary:        A General Framework for Graph Optimization

License:        BSD
URL:            https://github.com/RainerKuemmerle/g2o
Source0:        https://github.com/RainerKuemmerle/g2o/archive/%{gittag}/%{name}-%{version}.tar.gz
Patch0:         g2o.libsuffix.patch

Conflicts:      ros-kinetic-libg2o
Obsoletes:      ros-kinetic-libg2o <= 2016.4.24-1

BuildRequires:  boost-devel
BuildRequires:  cmake
BuildRequires:  eigen3-devel
BuildRequires:  gcc-c++
BuildRequires:  lapack-devel
BuildRequires:  mesa-libGL-devel
BuildRequires:  mesa-libGLU-devel
BuildRequires:  openblas-devel
BuildRequires:  suitesparse-devel

%description
The libg2o library from http://openslam.org/g2o.html

%prep
%autosetup -p1 -n %{name}-%{gittag}

%build
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

%cmake_build

%install
pushd obj-%{_target_platform}
%cmake_install

%files
%{_bindir}/*
%{_libdir}/*
%{_includedir}/*

%changelog
* Sat Jun 25 2022 Nicolas Limpert <limpert@fh-aachen.de> - 2020.12.23-1
- Update to recent version

* Wed Oct 09 2019 Till Hofmann <hofmann@kbsg.rwth-aachen.de> - 2017.07.30-2
- Remove unnecessary Requires

* Wed Oct 09 2019 Till Hofmann <hofmann@kbsg.rwth-aachen.de> - 2017.07.30-1
- Update to latest release

* Thu May 04 2017 Till Hofmann <till.hofmann@posteo.de> - 2016.4.24-3
- Add missing BR: openblas-devel, lapack-devel

* Wed May 03 2017 Till Hofmann <till.hofmann@posteo.de> - 2016.4.24-2
- Rename to g2o
- Switch to repository RainerKuemmerle/g2o
- Clean up Spec file

* Tue May 02 2017 Nicolas Limpert <nicolas.limpert@alumni.fh-aachen.de> - 2016.4.24-1
- changed install-target to /usr

* Mon Apr 25 2016 Vincent Rabaud <vincent.rabaud@gmail.com> - 2016.4.24-0
- Autogenerated by Bloom

* Mon Apr 25 2016 Vincent Rabaud <vincent.rabaud@gmail.com> - 2016.4.12-0
- Autogenerated by Bloom

