Name:           ros-kinetic-libg2o
Version:        2016.4.24
Release:        1%{?dist}
Summary:        ROS libg2o package

Group:          Development/Libraries
License:        BSD
URL:            https://github.com/RainerKuemmerle/g2o
Source0:        %{name}-%{version}.tar.gz
Patch0:         libg2o.libsuffix.patch

Requires:       boost-devel
Requires:       eigen3-devel
Requires:       mesa-libGL-devel
Requires:       mesa-libGLU-devel
#Requires:       ros-kinetic-catkin
Requires:       suitesparse-devel
BuildRequires:  boost-devel
BuildRequires:  cmake
BuildRequires:  eigen3-devel
BuildRequires:  mesa-libGL-devel
BuildRequires:  mesa-libGLU-devel
BuildRequires:  suitesparse-devel

%description
The libg2o library from http://openslam.org/g2o.html

%prep
%autosetup -p1 -n libg2o-release-release-kinetic-libg2o-2016.4.24-0

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
#if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
#if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
%{_bindir}/*
%{_libdir}/*
%{_includedir}/*

%changelog
* Tue May 02 2017 Nicolas Limpert <nicolas.limpert@alumni.fh-aachen.de> - 2016.4.24-1
- changed install-target to /usr

* Mon Apr 25 2016 Vincent Rabaud <vincent.rabaud@gmail.com> - 2016.4.24-0
- Autogenerated by Bloom

* Mon Apr 25 2016 Vincent Rabaud <vincent.rabaud@gmail.com> - 2016.4.12-0
- Autogenerated by Bloom

